/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatGuessRouteImport } from './routes/stat-guess'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PokechainRouteImport } from './routes/pokechain'
import { Route as PathFinderRouteImport } from './routes/path-finder'
import { Route as HowToPlayRouteRouteImport } from './routes/how-to-play/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DailyIndexRouteImport } from './routes/daily/index'
import { Route as HowToPlayStatGuessRouteImport } from './routes/how-to-play/stat-guess'
import { Route as HowToPlayPokechainRouteImport } from './routes/how-to-play/pokechain'
import { Route as HowToPlayPathFinderRouteImport } from './routes/how-to-play/path-finder'
import { Route as HowToPlayDailyRouteImport } from './routes/how-to-play/daily'
import { Route as HowToPlaySplatRouteImport } from './routes/how-to-play/$'
import { Route as DailyArchiveRouteImport } from './routes/daily/archive'

const StatGuessRoute = StatGuessRouteImport.update({
  id: '/stat-guess',
  path: '/stat-guess',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PokechainRoute = PokechainRouteImport.update({
  id: '/pokechain',
  path: '/pokechain',
  getParentRoute: () => rootRouteImport,
} as any)
const PathFinderRoute = PathFinderRouteImport.update({
  id: '/path-finder',
  path: '/path-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayRouteRoute = HowToPlayRouteRouteImport.update({
  id: '/how-to-play',
  path: '/how-to-play',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyIndexRoute = DailyIndexRouteImport.update({
  id: '/daily/',
  path: '/daily/',
  getParentRoute: () => rootRouteImport,
} as any)
const HowToPlayStatGuessRoute = HowToPlayStatGuessRouteImport.update({
  id: '/stat-guess',
  path: '/stat-guess',
  getParentRoute: () => HowToPlayRouteRoute,
} as any)
const HowToPlayPokechainRoute = HowToPlayPokechainRouteImport.update({
  id: '/pokechain',
  path: '/pokechain',
  getParentRoute: () => HowToPlayRouteRoute,
} as any)
const HowToPlayPathFinderRoute = HowToPlayPathFinderRouteImport.update({
  id: '/path-finder',
  path: '/path-finder',
  getParentRoute: () => HowToPlayRouteRoute,
} as any)
const HowToPlayDailyRoute = HowToPlayDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => HowToPlayRouteRoute,
} as any)
const HowToPlaySplatRoute = HowToPlaySplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => HowToPlayRouteRoute,
} as any)
const DailyArchiveRoute = DailyArchiveRouteImport.update({
  id: '/daily/archive',
  path: '/daily/archive',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/how-to-play': typeof HowToPlayRouteRouteWithChildren
  '/path-finder': typeof PathFinderRoute
  '/pokechain': typeof PokechainRoute
  '/settings': typeof SettingsRoute
  '/stat-guess': typeof StatGuessRoute
  '/daily/archive': typeof DailyArchiveRoute
  '/how-to-play/$': typeof HowToPlaySplatRoute
  '/how-to-play/daily': typeof HowToPlayDailyRoute
  '/how-to-play/path-finder': typeof HowToPlayPathFinderRoute
  '/how-to-play/pokechain': typeof HowToPlayPokechainRoute
  '/how-to-play/stat-guess': typeof HowToPlayStatGuessRoute
  '/daily': typeof DailyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/how-to-play': typeof HowToPlayRouteRouteWithChildren
  '/path-finder': typeof PathFinderRoute
  '/pokechain': typeof PokechainRoute
  '/settings': typeof SettingsRoute
  '/stat-guess': typeof StatGuessRoute
  '/daily/archive': typeof DailyArchiveRoute
  '/how-to-play/$': typeof HowToPlaySplatRoute
  '/how-to-play/daily': typeof HowToPlayDailyRoute
  '/how-to-play/path-finder': typeof HowToPlayPathFinderRoute
  '/how-to-play/pokechain': typeof HowToPlayPokechainRoute
  '/how-to-play/stat-guess': typeof HowToPlayStatGuessRoute
  '/daily': typeof DailyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/how-to-play': typeof HowToPlayRouteRouteWithChildren
  '/path-finder': typeof PathFinderRoute
  '/pokechain': typeof PokechainRoute
  '/settings': typeof SettingsRoute
  '/stat-guess': typeof StatGuessRoute
  '/daily/archive': typeof DailyArchiveRoute
  '/how-to-play/$': typeof HowToPlaySplatRoute
  '/how-to-play/daily': typeof HowToPlayDailyRoute
  '/how-to-play/path-finder': typeof HowToPlayPathFinderRoute
  '/how-to-play/pokechain': typeof HowToPlayPokechainRoute
  '/how-to-play/stat-guess': typeof HowToPlayStatGuessRoute
  '/daily/': typeof DailyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/how-to-play'
    | '/path-finder'
    | '/pokechain'
    | '/settings'
    | '/stat-guess'
    | '/daily/archive'
    | '/how-to-play/$'
    | '/how-to-play/daily'
    | '/how-to-play/path-finder'
    | '/how-to-play/pokechain'
    | '/how-to-play/stat-guess'
    | '/daily'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/how-to-play'
    | '/path-finder'
    | '/pokechain'
    | '/settings'
    | '/stat-guess'
    | '/daily/archive'
    | '/how-to-play/$'
    | '/how-to-play/daily'
    | '/how-to-play/path-finder'
    | '/how-to-play/pokechain'
    | '/how-to-play/stat-guess'
    | '/daily'
  id:
    | '__root__'
    | '/'
    | '/how-to-play'
    | '/path-finder'
    | '/pokechain'
    | '/settings'
    | '/stat-guess'
    | '/daily/archive'
    | '/how-to-play/$'
    | '/how-to-play/daily'
    | '/how-to-play/path-finder'
    | '/how-to-play/pokechain'
    | '/how-to-play/stat-guess'
    | '/daily/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HowToPlayRouteRoute: typeof HowToPlayRouteRouteWithChildren
  PathFinderRoute: typeof PathFinderRoute
  PokechainRoute: typeof PokechainRoute
  SettingsRoute: typeof SettingsRoute
  StatGuessRoute: typeof StatGuessRoute
  DailyArchiveRoute: typeof DailyArchiveRoute
  DailyIndexRoute: typeof DailyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stat-guess': {
      id: '/stat-guess'
      path: '/stat-guess'
      fullPath: '/stat-guess'
      preLoaderRoute: typeof StatGuessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokechain': {
      id: '/pokechain'
      path: '/pokechain'
      fullPath: '/pokechain'
      preLoaderRoute: typeof PokechainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/path-finder': {
      id: '/path-finder'
      path: '/path-finder'
      fullPath: '/path-finder'
      preLoaderRoute: typeof PathFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play': {
      id: '/how-to-play'
      path: '/how-to-play'
      fullPath: '/how-to-play'
      preLoaderRoute: typeof HowToPlayRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/': {
      id: '/daily/'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof DailyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-to-play/stat-guess': {
      id: '/how-to-play/stat-guess'
      path: '/stat-guess'
      fullPath: '/how-to-play/stat-guess'
      preLoaderRoute: typeof HowToPlayStatGuessRouteImport
      parentRoute: typeof HowToPlayRouteRoute
    }
    '/how-to-play/pokechain': {
      id: '/how-to-play/pokechain'
      path: '/pokechain'
      fullPath: '/how-to-play/pokechain'
      preLoaderRoute: typeof HowToPlayPokechainRouteImport
      parentRoute: typeof HowToPlayRouteRoute
    }
    '/how-to-play/path-finder': {
      id: '/how-to-play/path-finder'
      path: '/path-finder'
      fullPath: '/how-to-play/path-finder'
      preLoaderRoute: typeof HowToPlayPathFinderRouteImport
      parentRoute: typeof HowToPlayRouteRoute
    }
    '/how-to-play/daily': {
      id: '/how-to-play/daily'
      path: '/daily'
      fullPath: '/how-to-play/daily'
      preLoaderRoute: typeof HowToPlayDailyRouteImport
      parentRoute: typeof HowToPlayRouteRoute
    }
    '/how-to-play/$': {
      id: '/how-to-play/$'
      path: '/$'
      fullPath: '/how-to-play/$'
      preLoaderRoute: typeof HowToPlaySplatRouteImport
      parentRoute: typeof HowToPlayRouteRoute
    }
    '/daily/archive': {
      id: '/daily/archive'
      path: '/daily/archive'
      fullPath: '/daily/archive'
      preLoaderRoute: typeof DailyArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HowToPlayRouteRouteChildren {
  HowToPlaySplatRoute: typeof HowToPlaySplatRoute
  HowToPlayDailyRoute: typeof HowToPlayDailyRoute
  HowToPlayPathFinderRoute: typeof HowToPlayPathFinderRoute
  HowToPlayPokechainRoute: typeof HowToPlayPokechainRoute
  HowToPlayStatGuessRoute: typeof HowToPlayStatGuessRoute
}

const HowToPlayRouteRouteChildren: HowToPlayRouteRouteChildren = {
  HowToPlaySplatRoute: HowToPlaySplatRoute,
  HowToPlayDailyRoute: HowToPlayDailyRoute,
  HowToPlayPathFinderRoute: HowToPlayPathFinderRoute,
  HowToPlayPokechainRoute: HowToPlayPokechainRoute,
  HowToPlayStatGuessRoute: HowToPlayStatGuessRoute,
}

const HowToPlayRouteRouteWithChildren = HowToPlayRouteRoute._addFileChildren(
  HowToPlayRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HowToPlayRouteRoute: HowToPlayRouteRouteWithChildren,
  PathFinderRoute: PathFinderRoute,
  PokechainRoute: PokechainRoute,
  SettingsRoute: SettingsRoute,
  StatGuessRoute: StatGuessRoute,
  DailyArchiveRoute: DailyArchiveRoute,
  DailyIndexRoute: DailyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
